// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dubttmzyuklpjejtimdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1YnR0bXp5dWtscGplanRpbWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM0MDI4NzQsImV4cCI6MjA0ODk3ODg3NH0.YBvaVJAhKJL_Hn-qJhZJZQJZJZJZJZJZJZJZJZJZJZJZ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});